export const MODULE_LIST = [
    /* 👤 User Module*/
    {
        name: 'user_create',
        alias_name: 'user',
        display_name: 'Create Users',
        description: 'Allows creating new users',
        category: 'User Management',
        status: 1,
    },
    {
        name: 'user_update',
        alias_name: 'user',
        display_name: 'Update Users',
        description: 'Allows editing user details',
        category: 'User Management',
        status: 1,
    },
    {
        name: 'user_delete',
        alias_name: 'user',
        display_name: 'Delete Users',
        description: 'Allows removing users',
        category: 'User Management',
        status: 1,
    },
    {
        name: 'user_list',
        alias_name: 'user',
        display_name: 'List Users',
        description: 'Allows viewing the list of users',
        category: 'User Management',
        status: 1,
    },

    // ✍️ Author Module
    {
        name: 'author_create',
        alias_name: 'author',
        display_name: 'Create Authors',
        description: 'Allows adding new authors',
        category: 'Author Management',
        status: 1,
    },
    {
        name: 'author_update',
        alias_name: 'author',
        display_name: 'Update Authors',
        description: 'Allows editing author details',
        category: 'Author Management',
        status: 1,
    },
    {
        name: 'author_delete',
        alias_name: 'author',
        display_name: 'Delete Authors',
        description: 'Allows removing authors',
        category: 'Author Management',
        status: 1,
    },
    {
        name: 'author_list',
        alias_name: 'author',
        display_name: 'List Authors',
        description: 'Allows viewing the list of authors',
        category: 'Author Management',
        status: 1,
    },

    // 📖 Book Module
    {
        name: 'book_create',
        alias_name: 'book',
        display_name: 'Create Books',
        description: 'Allows adding new books',
        category: 'Book Management',
        status: 1,
    },
    {
        name: 'book_update',
        alias_name: 'book',
        display_name: 'Update Books',
        description: 'Allows editing book details',
        category: 'Book Management',
        status: 1,
    },
    {
        name: 'book_delete',
        alias_name: 'book',
        display_name: 'Delete Books',
        description: 'Allows removing books',
        category: 'Book Management',
        status: 1,
    },
    {
        name: 'book_list',
        alias_name: 'book',
        display_name: 'List Books',
        description: 'Allows viewing the list of books',
        category: 'Book Management',
        status: 1,
    },

    // 🗓️ Semester Module
    {
        name: 'semester_create',
        alias_name: 'semester',
        display_name: 'Create Semesters',
        description: 'Allows adding new semesters',
        category: 'Semester Management',
        status: 1,
    },
    {
        name: 'semester_update',
        alias_name: 'semester',
        display_name: 'Update Semesters',
        description: 'Allows editing semester details',
        category: 'Semester Management',
        status: 1,
    },
    {
        name: 'semester_delete',
        alias_name: 'semester',
        display_name: 'Delete Semesters',
        description: 'Allows removing semesters',
        category: 'Semester Management',
        status: 1,
    },
    {
        name: 'semester_list',
        alias_name: 'semester',
        display_name: 'List Semesters',
        description: 'Allows viewing the list of semesters',
        category: 'Semester Management',
        status: 1,
    },

    // 📚 Course Module
    {
        name: 'course_create',
        alias_name: 'course',
        display_name: 'Create Courses',
        description: 'Allows adding new courses',
        category: 'Course Management',
        status: 1,
    },
    {
        name: 'course_update',
        alias_name: 'course',
        display_name: 'Update Courses',
        description: 'Allows editing course details',
        category: 'Course Management',
        status: 1,
    },
    {
        name: 'course_delete',
        alias_name: 'course',
        display_name: 'Delete Courses',
        description: 'Allows removing courses',
        category: 'Course Management',
        status: 1,
    },
    {
        name: 'course_list',
        alias_name: 'course',
        display_name: 'List Courses',
        description: 'Allows viewing the list of courses',
        category: 'Course Management',
        status: 1,
    },

    // 🏷️ Category Module
    {
        name: 'category_create',
        alias_name: 'category',
        display_name: 'Create Categories',
        description: 'Allows adding new categories',
        category: 'Category Management',
        status: 1,
    },
    {
        name: 'category_update',
        alias_name: 'category',
        display_name: 'Update Categories',
        description: 'Allows editing category details',
        category: 'Category Management',
        status: 1,
    },
    {
        name: 'category_delete',
        alias_name: 'category',
        display_name: 'Delete Categories',
        description: 'Allows removing categories',
        category: 'Category Management',
        status: 1,
    },
    {
        name: 'category_list',
        alias_name: 'category',
        display_name: 'List Categories',
        description: 'Allows viewing the list of categories',
        category: 'Category Management',
        status: 1,
    },
];
